/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PoliciesTermsRouteImport } from './routes/policies.terms'
import { Route as PoliciesReturnsRouteImport } from './routes/policies.returns'
import { Route as PoliciesPrivacyRouteImport } from './routes/policies.privacy'
import { Route as ShopCategorySubRouteImport } from './routes/shop.$category.$sub'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesTermsRoute = PoliciesTermsRouteImport.update({
  id: '/policies/terms',
  path: '/policies/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesReturnsRoute = PoliciesReturnsRouteImport.update({
  id: '/policies/returns',
  path: '/policies/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyRoute = PoliciesPrivacyRouteImport.update({
  id: '/policies/privacy',
  path: '/policies/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategorySubRoute = ShopCategorySubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => ShopCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/wishlist': typeof WishlistRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$category': typeof ShopCategoryRouteWithChildren
  '/shop/$category/$sub': typeof ShopCategorySubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/wishlist': typeof WishlistRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$category': typeof ShopCategoryRouteWithChildren
  '/shop/$category/$sub': typeof ShopCategorySubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/wishlist': typeof WishlistRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$category': typeof ShopCategoryRouteWithChildren
  '/shop/$category/$sub': typeof ShopCategorySubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/wishlist'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/terms'
    | '/product/$id'
    | '/shop/$category'
    | '/shop/$category/$sub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/wishlist'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/terms'
    | '/product/$id'
    | '/shop/$category'
    | '/shop/$category/$sub'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/wishlist'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/terms'
    | '/product/$id'
    | '/shop/$category'
    | '/shop/$category/$sub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  WishlistRoute: typeof WishlistRoute
  PoliciesPrivacyRoute: typeof PoliciesPrivacyRoute
  PoliciesReturnsRoute: typeof PoliciesReturnsRoute
  PoliciesTermsRoute: typeof PoliciesTermsRoute
  ProductIdRoute: typeof ProductIdRoute
  ShopCategoryRoute: typeof ShopCategoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/terms': {
      id: '/policies/terms'
      path: '/policies/terms'
      fullPath: '/policies/terms'
      preLoaderRoute: typeof PoliciesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/returns': {
      id: '/policies/returns'
      path: '/policies/returns'
      fullPath: '/policies/returns'
      preLoaderRoute: typeof PoliciesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy': {
      id: '/policies/privacy'
      path: '/policies/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof PoliciesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category/$sub': {
      id: '/shop/$category/$sub'
      path: '/$sub'
      fullPath: '/shop/$category/$sub'
      preLoaderRoute: typeof ShopCategorySubRouteImport
      parentRoute: typeof ShopCategoryRoute
    }
  }
}

interface ShopCategoryRouteChildren {
  ShopCategorySubRoute: typeof ShopCategorySubRoute
}

const ShopCategoryRouteChildren: ShopCategoryRouteChildren = {
  ShopCategorySubRoute: ShopCategorySubRoute,
}

const ShopCategoryRouteWithChildren = ShopCategoryRoute._addFileChildren(
  ShopCategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  WishlistRoute: WishlistRoute,
  PoliciesPrivacyRoute: PoliciesPrivacyRoute,
  PoliciesReturnsRoute: PoliciesReturnsRoute,
  PoliciesTermsRoute: PoliciesTermsRoute,
  ProductIdRoute: ProductIdRoute,
  ShopCategoryRoute: ShopCategoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
